---
# https://ctrlnotes.com/vagrant-advanced-examples/#-inventory-generated-by-vagrant-custom-groups-are-added-to-the-generated-inventory
all:
  hosts:
    # 10.0.5.[5:123]:
  children:
    kube_control:
      hosts:
        10.0.5.10:
     kube_workers:
      hosts:
        10.0.5.10:
        10.0.5.102:
        #10.0.5.[101:102]:
